### ISSUE TITLE
Add project page

### ISSUE THREAD

**Issue by rinse0ut** [CodeHubOrg/javascript101#19]
Please add a basic projects page that showcases the following projects:

- javascript101.co.uk
- Organisation's database
- Today I learned
- React Lab

Each project should have a title, description and link to the repo.

You can either use a mark down file in the docs directory or a custom pug template.

**Comment by STRAYKR** [comment]
PR #38 adds all projects from Github. I will showcase the 4x others above next.

**Comment by rinse0ut** [comment]
Nice work Tim.  First issue complete!
