### ISSUE TITLE
Create a git-playground repository

### ISSUE THREAD

**Issue by rinse0ut** [CodeHubOrg/javascript101#20]
We need a git playground repository for members to practise using git.

Please could you:

- Create a git-playground repository on your personal github account called 'git-playground'
- Create an index.html file with basic mark up including a 'Hall of Fame' title and a list with your name on it 
- Create a README.md file outlines the purpose of the repo and the following exercise:

**Documentation**
[How to use git](https://github.com/CodeHubOrg/javascript101/blob/master/docs/git.md)
[How to make pull requests](https://docs.google.com/presentation/d/12XPsgBkarJLA6I1UJd7HK1izUpQfX2Lt2gQq91z9XNQ/edit?usp=sharing)

**Pull Requests Exercise**
1. Fork this git playground project.
2. Update the hall of fame with your name.
3. Create a pull request.
4. Update your github with the changes. 

Further info on writing a README file:
[The art of README](https://github.com/noffle/art-of-readme)

Once this is complete please fork the project on CodeHubOrg.

If you need any help just ask on Gitter :)

**Comment by Nat47** [comment]
Hey Dave,


Hope you are well!


I am on it,


Thank you! :)


________________________________
De: Dave Thomson <notifications@github.com>
Enviado: miércoles, 22 de marzo de 2017 10:29 p. m.
Para: CodeHubOrg/javascript101
Cc: Nat47; Mention
Asunto: Re: [CodeHubOrg/javascript101] Create a git-playground repository (#20)


Assigned #20<https://github.com/CodeHubOrg/javascript101/issues/20> to @Nat47<https://github.com/Nat47>.

**Comment by rinse0ut** [comment]
Hey Nat,

I'm good thanks.  Hope you had a good weekend.

If you need any help just let me know on Gitter.

Cheers!

**Comment by rinse0ut** [comment]
Thanks for doing this @Nat47.  The CodeHubOrg repo is missiing the index.html file.  Please update with a pull request.
