### ISSUE TITLE
Update contact nav link to mailto 

### ISSUE THREAD

**Issue by rinse0ut** [CodeHubOrg/javascript101#21]
Please update the contact nav link so that it opens the mail to link directly instead of opening a page template in the following file:

/public/partials/nav.html

**Comment by STRAYKR** [comment]
PR #49

**Comment by rinse0ut** [comment]
Thanks for doing this.

@trianah had said she was doing this, so will wait on that for the moment.

**Comment by trianah** [comment]
Hi, I have sent the PR, hope it's ok. I don't know how to assign myself to an issue, or is it an admin who should do this?

**Comment by rinse0ut** [comment]
Thanks.  @katjad Should have invited you to join the group.  I'll check.

**Comment by trianah** [comment]
Cool thanks, maybe she added my other account cause I just realised I accidentally made two accounts.

**Comment by rinse0ut** [comment]
Please add a subject to the email as follows:

Hello :-)

As per TIm's pull request.
