### ISSUE TITLE
Presentations Page

### ISSUE THREAD

**Issue by rinse0ut** [CodeHubOrg/javascript101#23]
Please add a presentations page based on the following mark down file:
https://github.com/rinse0ut/javascript101-handbook/blob/master/presentations.md

- Amend the description as you see fit

- Save the file to the docs folder

- Add a route based in the same way as the 'about' page in routes.js

**Comment by BrendanCostigan** [comment]
Started having a look at how to do this ...

**Comment by rinse0ut** [comment]
Would be good to have archived presentations, future presentations and needed presentations.

Also something about why it is good to do a presentation, even if you don't know much about a topic etc.
