### ISSUE TITLE
Best Practises Page

### ISSUE THREAD

**Issue by rinse0ut** [CodeHubOrg/javascript101#28]
Please create a markdown page explaining best practises and their benefits or a short intro and a link to a blog article.

Could base it on the [handbook page](https://github.com/rinse0ut/javascript101-handbook/blob/master/best_practices.md)

route: /best-practises

**Comment by rinse0ut** [comment]
Please add content from handbook page.

**Comment by tbuyus** [comment]
I have put a stub in.
