### ISSUE TITLE
Random Quote Mixin

### ISSUE THREAD

**Issue by rinse0ut** [CodeHubOrg/javascript101#31]
Create a random quote mixin for the home page for the inspiration, god father and funsies features.

**Comment by STRAYKR** [comment]
So like a function that takes an array and returns a random entry from that array? or is this more than that... not really familiar with mixins in this context.

**Comment by rinse0ut** [comment]
Yes that's right.  For example the logos on the home page use a mixin:

Mixin:
https://github.com/CodeHubOrg/javascript101/blob/master/views/mixins/logoList.pug

Data:
https://github.com/CodeHubOrg/javascript101/blob/master/model/logo.js

Controller:
https://github.com/CodeHubOrg/javascript101/blob/master/routes.js line **10**

Template:
https://github.com/CodeHubOrg/javascript101/blob/master/views/index.pug **line 16**

[Mixin tutorial example](https://www.sitepoint.com/jade-tutorial-for-beginners/#mixins)

**Comment by rinse0ut** [comment]
Quotes can be found in the shared content plan.

**Comment by STRAYKR** [comment]
Got the random quote working... just need the quotes to include. Whats the 'shared content plan' ?
