### ISSUE TITLE
Add How to Contribute Home Page Feature

### ISSUE THREAD

**Issue by rinse0ut** [CodeHubOrg/javascript101#36]
Please add a how to contribute home page feature with a link to this issue list.

In the description mention that we also need the pages proof read and welcome feedback, suggestions and pull requests.

**Comment by STRAYKR** [comment]
Added to PR #38

**Comment by rinse0ut** [comment]
Just to sort the formatting and highlight this.  Please could you make this feature full page width and make the button red and large to read 'Contribute' and move the 'In Bristol and into JavaScript' feature below the block of 8 features.

Please keep pull requests one per issue. Thanks.

**Comment by rinse0ut** [comment]
Nice work Tim, thanks.
