### ISSUE TITLE
Add Sponsors to Home Page

### ISSUE THREAD

**Issue by rinse0ut** [CodeHubOrg/javascript101#40]
As per https://www.meetup.com/CodeHub-Bristol/

**Comment by trianah** [comment]
@rinse0ut I added the sponsors to the home page but accidentally pushed my branch to upstream (oops)

**Comment by rinse0ut** [comment]
@trianah Great, well done thanks.  I've noticed you have created a new sponsors mixin which duplicates the functionality of the logoList mixin without the responsive classes.  Please could you use the logoList mixin instead (so that we keep things DRY) and remove the sponsors mixin.   You might have to add an extra parameter for the css class name to the LogoList mixin.

Once that's done please make a pull request.  Please delete your branch from upstream.  (`git push updstream --delete sponsors`)

**Comment by rinse0ut** [comment]
Please move the sponsors section to above the 'How to contribute' section.

**Comment by rinse0ut** [comment]
Closing as per our discussion about formatting at the hack night.
