### ISSUE TITLE
Style Headlines

### ISSUE THREAD

**Issue by rinse0ut** [CodeHubOrg/javascript101#46]
Style headlines with yellow background and black text as per JS logo.

Add faded JS code to header background.

Nice to have: if there is an actual JS script being used on the page use that as background using something like https://highlightjs.org/

**Comment by STRAYKR** [comment]
What do you mean by headlines Dave?

What is the header background? The area including the welcome to JS101 title and the Started, Meetup and Resources buttons?

**Comment by rinse0ut** [comment]
The headlines in the h1 tags on the standard pages.

This is not for the home page at the moment, will make another issue for that.

For example: https://scotch.io/tutorials

**Comment by trianah** [comment]
I made a quick mockup of the header on my last PR  #71 . Is that what you mean, @rinse0ut?

**Comment by rinse0ut** [comment]
Yes that's spot on.  Please implement it.

**Comment by trianah** [comment]
@rinse0ut Ok I have the code but before I send a PR, this heading only for the markdown pages right?

**Comment by rinse0ut** [comment]
@trianah Yes that's right thanks.
