### ISSUE TITLE
Inconsistent Nav links across pages.

### ISSUE THREAD

**Issue by rinse0ut** [CodeHubOrg/javascript101#56]
`public/partials/nav.html` should be used for all page templates

**Comment by trianah** [comment]
@rinse0ut  I created the pug file and routes entry for the projects page, it uses the same footer and nav bar as the home page. Now the only page that is not using the nav.html template is the resources page (it has a hardcoded nav bar), are we creating a pug file for that page too? If so I'll create the file and send a PR for changes on both pages.

**Comment by rinse0ut** [comment]
@trianah Great thanks.  The resources page is going to be replaced by the React project that @katjad, @wingedeel and @Gicela are working on.  It would be great if you could convert it to a pug template as it's not ready yet.

**Comment by trianah** [comment]
Ok
