### ISSUE TITLE
Styling the Homepage

### ISSUE THREAD

**Issue by katjad** [CodeHubOrg/javascript101#75]
Create a more individual style my modifying some of the bootstrap styles
Things we've discussed:
- Custom fonts for the headers
- Button styling, move buttons apart where they are stuck together
- Spacing
- Possibly make logos a bit smaller 
- Fix the footer

**Comment by trianah** [comment]
![calluna](https://cloud.githubusercontent.com/assets/21130327/25590570/02eedb36-2ea9-11e7-898e-10db57075ea0.png)
![roboto](https://cloud.githubusercontent.com/assets/21130327/25590569/02eae256-2ea9-11e7-9881-a92a2975993e.png)

**Comment by trianah** [comment]
@katjad I attached a screenshot of the changes before I send the PR. There are two files, one uses the Calluna typography for the titles (the one we picked last Tuesday), the other uses Roboto. What do you think?

**Comment by katjad** [comment]
Nice!!! I really like the Calluna. Which one do you prefer? Yes, please create a pull request :)

**Comment by trianah** [comment]
Ok, I think I like Calluna too but been staring at it for so long that I wasn't sure for a minute.
