### ISSUE TITLE
Live Release

### ISSUE THREAD

**Issue by rinse0ut** [CodeHubOrg/javascript101#81]
Create live branch and sort out content.

**Comment by rinse0ut** [comment]
We agreed to get rid of the generic 'view details' button as this is a UX anti pattern.  Instead use a semantic action or block link the whole div with highlight / shade change.

Get rid of the poll, gallery and quotes as well?

**Comment by Gicela** [comment]
Yep. I'd like to keep the quotes, but they are not high priority at the moment. We could integrate later on.

**Comment by katjad** [comment]
Please leave quotes and jokes :)

**Comment by Gicela** [comment]
Happy to keep quotes and jokes. You could add a panel for each on the homepage in a similar style to the rest and include them before the logos??

**Comment by rinse0ut** [comment]
Well done Katja on getting it live!
