### ISSUE TITLE
What we do? -homepage

### ISSUE THREAD

**Issue by Gicela** [CodeHubOrg/javascript101#90]
I think it might be good to have the headings for the 'what we do' section as links to the pages. However, we still need to write the content for these. 

I tried to add a link to the h2 heading with the simple tags and got some silly errors. Got frustrated and gave up! Can someone add an example on how to do this? I could do the rest. 
We might not have time to write all the pages for the live version though. It might be best to leave without links for now. What do people think?

**Comment by rinse0ut** [comment]
Here is the pug syntax for a h2 link:

```
    a(href='/what-we-do') 
      h2 What we do
```

**Comment by rinse0ut** [comment]
Link added in PR #91

**Comment by rinse0ut** [comment]
We could keep it simple and just not link to any sections from the features page for the moment.

However I think we could get the content sorted based on handbook content, internet resources etc.

If so we need some cool css3 box animations to signify a link and to make the headline link to what we do better.

Icons / bg image would be ideal for each section.

**Comment by Gicela** [comment]
For now I have left the links on the headings
@katjad Do you think you could add a little blurb on each of the pages?

**Comment by rinse0ut** [comment]
@katjad @Gicela I've added some stuff from the handbook on each page.  Would be great if you could add to it.

**Comment by katjad** [comment]
@rinse0ut @gicela - I am wondering if we should have fewer under 'What we do' (perhaps Presentations, Pair programming, Code Reviews, Collaborating), and put links to the other pages somewhere else - I totally love the 'Best practices' page btw @rinse0ut ! But I wonder if it is really so much what we do, it is more how we do things - or how we are supposed to do them ;) -- Think overall structure of site could perhaps be a bit different, will try to get something to you soon. Coming days busy, but will try to fit it in!

**Comment by Gicela** [comment]
I agree that we don't need too many pages for the 'what we do' section. However, I think we should leave the What we do panel on the homepage. We could leave the links on the 'What we do' panel with anchor links and small blur for each thing??  All linking to one 'what we do' page.

**Comment by katjad** [comment]
@Gicela Thanks for your comment on GItter, @rinse0ut if you agree too I'll create a pull request just for that section. I have reserved Tuesday morning to further work on the site, I want to create one page that has short paragraphs on each topic, possibly pull in from the different doc/ files of the repository. Where we have more content, we can then link to a further page.

**Comment by katjad** [comment]
@Gicela @rinse0ut Just adding this here as does not have its own issue, and don't think it needs one: I think I'd not link to my write-ups from the homepage. We can link to it but not sure I'd make it one of the first links. I quite like having just one link for each section. So there's a button for 'getting started', next section 'sign up' for next meetup, then gitter, then section learn about what we do.. Each one just a single call to action. What do you think? Could include that in pull request

**Comment by Gicela** [comment]
@katjad I think it is a good idea to have a link to the meetups archive. Some good info there. I added to the homepage because it just easy to get to, otherwise it gets buried among other stuff. 
I'd like the 'Get started' button at the top back as that's the page we are linking to. It was labelled correctly and easy to identify by new people.
