### ISSUE TITLE
Master branch error

### ISSUE THREAD

**Issue by Gicela** [CodeHubOrg/javascript101#94]
Just pulling the master branch and get the following error:
TypeError: /javascript101/views/mixins/logoList.pug:9
    7|   div.logos
    8|     ul(class="row")
  > 9|       for logo in logoList
    10|         +logo(logo)
    11| 

Cannot read property 'length' of undefined

Could you have a look please?

**Comment by rinse0ut** [comment]
Have you tried restarting your web server?

Just did a fresh clone and it runs fine.

**Comment by Gicela** [comment]
After a couple of restarts - it is all fine :)
Thanks!
