### ISSUE TITLE
Links for resources

### ISSUE THREAD

**Issue by Gicela** [CodeHubOrg/javascript101#97]
For now, we just need some useful links to add to our resources page. I have added a handful but ideally, I'd like you to share one link that you have found useful for learning JavaScript. It could be any resource type; video, article, book, etc. 

Thanks!

**Comment by rinse0ut** [comment]
Fun Fun Function (mpjme) on You Tube is an awesome channel.

Javascript Jabber is a good pod cast.

Javascript the good parts (it's a classic)
