### ISSUE TITLE
Remove email from top navigation

### ISSUE THREAD

**Issue by Gicela** [CodeHubOrg/javascript101#98]
Could we have a page with links to how people can get in touch?

Via Twitter @CodeHubBs 
Via Meetup
or codehubbristol@gmail.com

**Comment by rinse0ut** [comment]
A form as well?

**Comment by Gicela** [comment]
We could leave the form for version 2 [?] I don't really mind.

**Comment by katjad** [comment]
Think we don't need a form really, there are so many ways of getting in touch. We have info@codehub.org.uk as well btw.. We can use both, but should only list one on the site

**Comment by rinse0ut** [comment]
For the live release I think the current mailto is fine and can be enhanced on the next release.
